// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwYodlzmy-hEhiBP3owMg5d4n5x9tvRUc',
    appId: '1:401061764414:web:3c9af631e6e06cd922206f',
    messagingSenderId: '401061764414',
    projectId: 'chitchat-b28f2',
    authDomain: 'chitchat-b28f2.firebaseapp.com',
    storageBucket: 'chitchat-b28f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsw9enHbIIH3WJp9JvXE1g7Ay2a1v8tV4',
    appId: '1:401061764414:android:ce4b2cc2e95360fb22206f',
    messagingSenderId: '401061764414',
    projectId: 'chitchat-b28f2',
    storageBucket: 'chitchat-b28f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmYMqqWVVOZapeWfdCXwVSv_CJ2k0-52w',
    appId: '1:401061764414:ios:3bd72d8a64cec24422206f',
    messagingSenderId: '401061764414',
    projectId: 'chitchat-b28f2',
    storageBucket: 'chitchat-b28f2.appspot.com',
    iosClientId: '401061764414-6sfgcrv6ois1g11ms2lmufjqq5uekqjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitchat',
  );
}
